name: Api Deploy CI/CD

on:
  push:
    branches:
      - main

jobs:
  heroku-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Get actions
        uses: actions/checkout@v3
      - name: deploying to heroku
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
